repos:
  - repo: local
    hooks:
      - id: ruff
        name: Lint with ruff
        entry: uv run --extra dev ruff check
        language: system
        types: [python]
        files: ^(collect/|format/src/|processing/src/).*$

      - id: pyright
        name: Type check with pyright
        entry: uv run --extra dev pyright
        language: system
        types: [python]
        files: ^(collect/|format/src/|processing/src/).*$
