site_name: Red Rover
repo_url: https://github.com/WiseLabCMU/red-rover
repo_name: WiseLabCMU/red-rover
nav:
  - about: index.md
  - roverc:
    - About: roverc/index.md
    - User Guide:
      - Usage Instructions: roverc/instructions.md
      - Assembly: roverc/assembly.md
      - Setup & Configuration: roverc/setup.md
      - Data Collection Tips: roverc/tips.md
      - Manual Operation: roverc/usage.md
    - Internals:
      - Low Level CLI: roverc/cli.md
      - Roverc: roverc/internal.md
      - IMU API: roverc/imu.md
      - Flask App: roverc/flask.md
  - roverd:
    - About: roverd/index.md
    - Usage:
      - CLI: roverd/cli.md
      - API: roverd/api.md
      - Data Types: roverd/types.md
      - Transforms: roverd/transforms.md
    - Sensors:
      - Rover Sensors: roverd/sensors.md
      - Timestamps: roverd/timestamps.md
    - Channels:
      - Channel Types: roverd/channels.md
      - Utils: roverd/utils.md
  - roverp:
    - About: roverp/index.md
    - Graphics: roverp/graphics.md
  - i/q-1m:
    - About: iq1m/index.md
  - tss:
    - About: tss/index.md
    - API:
      - High Level API: tss/api.md
      - Stats: tss/stats.md
      - Utils: tss/utils.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    logo: material/video-wireless-outline
    annotation: material/arrow-right-circle
  font:
    code: monospace
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
  palette:
    primary: red
    accent: purple

plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        paths:
        - format/src
        - collect/
        - stats/src
        - processing/src
        options:
          docstring_style: google
          relative_crossrefs: true
          separate_signature: true
          line_length: 80
          show_signature_annotations: true
          signature_crossrefs: true
          show_root_full_path: true
          show_root_members_full_path: true
          show_symbol_type_heading: true
          show_root_heading: true
          show_root_toc_entry: true
          heading_level: 1
          preload_modules:
          - abstract_dataloader
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://wiselabcmu.github.io/abstract-dataloader/objects.inv
        - https://docs.pytorch.org/docs/stable/objects.inv
        - https://docs.jax.dev/en/latest/objects.inv
        - https://wiselabcmu.github.io/xwr/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
