lidar:
  type: lidar
  args:
    addr: null
    port_lidar: 7502
    port_imu: 7503
    fps: 10.0
    height: 64
imu:
  type: imu
  args:
    port: /dev/ttyUSB0
    baudrate: 115200
camera:
  type: camera
  args:
    idx: 0
    width: 1920
    height: 1080
    fps: 60.0
radar:
  type: radar
  args:
    radar:
      port: "/dev/ttyACM0"
      frequency: 77.0
      idle_time: 106.0
      adc_start_time: 6.0
      ramp_end_time: 58.22
      tx_start_time: 2.0
      freq_slope: 63.005
      adc_samples: 256
      sample_rate: 5000
      frame_length: 64
      frame_period: 32.0
    capture:
      sys_ip: 192.168.33.30
      fpga_ip: 192.168.33.180
      data_port: 4098
      config_port: 4096
      timeout: 1.0
      socket_buffer: 2048000
      delay: 5.0
