lidar:
  script: "lidar.py"
  args:
    addr: null
    port_lidar: 7502
    port_imu: 7503
    fps: 10.0
    height: 64
imu:
  script: "imu.py"
  args:
    port: /dev/ttyUSB0
    baudrate: 115200
camera:
  script: "camera.py"
  args:
    idx: 0
    width: 1920
    height: 1080
    fps: 60.0
radar:
  script: "radar.py"
  args:
    adc_samples: 256
    frame_length: 64
    fps: 10.0
