lidar:
  script: "sensors/lidar.py"
  args:
    addr: null
    port_lidar: 7502
    port_imu: 7503
    fps: 10.0
    height: 64
imu:
  script: "sensors/imu.py"
  args:
    port: /dev/ttyUSB0
    baudrate: 115200
camera:
  script: "sensors/camera.py"
  args:
    idx: 0
    width: 1920
    height: 1080
    fps: 60.0
